export const CREATE_IMAGE_REQUEST = 'CREATE_IMAGE_REQUEST'
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS'
export const CREATE_IMAGE_FAILURE = 'CREATE_IMAGE_FAILURE'


export const GET_IMAGE_REQUEST = 'GET_IMAGE_REQUEST'
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS'
export const GET_IMAGE_FAILURE = 'GET_IMAGE_FAILURE'

export const FIND_IMAGE_REQUEST = 'FIND_IMAGE_BY_IMAGE_REQUEST'
export const FIND_IMAGE_SUCCESS = 'FIND_IMAGE_BY_IMAGE_SUCCESS'
export const FIND_IMAGE_FAILURE = 'FIND_IMAGE_BY_IMAGE_FAILURE'